version: "3.8"
services:
  mongo:
    image: "mongo:latest"
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: toor
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: toor
  cwmp:
    image: "genieacs:latest"
    restart: always
    command: "genieacs-cwmp"
    ports:
      - "7547:7547"
    depends_on:
      - mongo
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: "mongodb://mongo/genieacs"
  nbi:
    image: "genieacs:latest"
    restart: always
    command: "genieacs-nbi"
    ports:
      - "7557:7557"
    depends_on:
      - mongo
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: "mongodb://mongo/genieacs"
  fs:
    image: "genieacs:latest"
    restart: always
    command: "genieacs-fs"
    ports:
      - "7567:7567"
    depends_on:
      - mongo
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: "mongodb://mongo/genieacs"
  ui:
    image: "genieacs:latest"
    restart: always
    command: "genieacs-ui --ui-jwt-secret secret"
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      GENIEACS_MONGODB_CONNECTION_URL: "mongodb://mongo/genieacs"
  
